//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBStokTakipEntities : DbContext
    {
        public DBStokTakipEntities()
            : base("name=DBStokTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TKategori> TKategori { get; set; }
        public virtual DbSet<TUrun> TUrun { get; set; }
        public virtual DbSet<TSatis> TSatis { get; set; }
    
        public virtual ObjectResult<AylikSatis_Result> AylikSatis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AylikSatis_Result>("AylikSatis");
        }
    
        public virtual ObjectResult<GunlukSatis_Result> GunlukSatis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GunlukSatis_Result>("GunlukSatis");
        }
    
        public virtual ObjectResult<YillikSatis_Result> YillikSatis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YillikSatis_Result>("YillikSatis");
        }
    
        public virtual ObjectResult<Nullable<decimal>> BuAyCiro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("BuAyCiro");
        }
    
        public virtual ObjectResult<Nullable<decimal>> BugunCiro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("BugunCiro");
        }
    }
}
